const {chromium}=require('playwright');
const assert=require('node:assert/strict');
const base=process.env.BASE_URL||'http://127.0.0.1:18080';
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
 const p=await b.newPage({viewport:{width:1280,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.addInitScript(()=>{window.audioStarts=0;window.vibrations=[];Object.defineProperty(navigator,'vibrate',{value:n=>{window.vibrations.push(n);return true;},configurable:true});for(const name of ['OscillatorNode','AudioBufferSourceNode']){const proto=window[name].prototype,original=proto.start;proto.start=function(...args){window.audioStarts++;return original.apply(this,args);};}});
 await p.goto(base+'/smash.html');await p.locator('#haptic').click();
 await p.locator('#action').click();await p.waitForTimeout(70);await p.locator('#action').click();await p.waitForTimeout(70);await p.locator('#action').click();assert.equal(await p.locator('#desk').getAttribute('data-broken'),'true');assert.ok(await p.evaluate(()=>audioStarts)>0);assert.ok(await p.evaluate(()=>vibrations.some(n=>n>0)));
 await p.locator('#again').click();assert.equal(await p.locator('#desk').getAttribute('data-broken'),'false');
 await p.locator('#sound').click();await p.locator('#haptic').click();const starts=await p.evaluate(()=>audioStarts),positive=await p.evaluate(()=>vibrations.filter(n=>n>0).length);await p.locator('#action').click();await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>audioStarts),starts);assert.equal(await p.evaluate(()=>vibrations.filter(n=>n>0).length),positive);await p.reload();assert.match(await p.locator('#sound').innerText(),/关/);
 await p.locator('[data-scene=bubbles]').click();await p.locator('#desk').scrollIntoViewIfNeeded();let r=await p.locator('#desk').boundingBox();const pt=(x,y)=>({x:r.x+x*r.width/720,y:r.y+y*r.height/460});let a=pt(94,74),z=pt(626,74);await p.mouse.move(a.x,a.y);await p.mouse.down();await p.mouse.move(z.x,z.y,{steps:2});await p.mouse.up();assert.equal(await p.locator('#desk').getAttribute('data-popped'),'8');await p.locator('#desk').focus();await p.keyboard.press('Space');assert.equal(await p.locator('#desk').getAttribute('data-popped'),'9');await p.locator('#again').click();assert.equal(await p.locator('#desk').getAttribute('data-popped'),'0');await p.screenshot({path:'.qa/smash-bubbles.png',fullPage:true});
 await p.locator('[data-scene=blocks]').click();await p.waitForTimeout(400);await p.locator('#desk').scrollIntoViewIfNeeded();r=await p.locator('#desk').boundingBox();a=pt(248,215);z=pt(570,130);await p.mouse.move(a.x,a.y);await p.mouse.down();assert.equal(await p.locator('#desk').getAttribute('data-dragging'),'true');await p.mouse.move(z.x,z.y,{steps:8});await p.mouse.up();assert.equal(await p.locator('#desk').getAttribute('data-dragging'),'false');const image=await p.locator('#desk').evaluate(c=>c.toDataURL());await p.waitForTimeout(200);assert.notEqual(await p.locator('#desk').evaluate(c=>c.toDataURL()),image);await p.locator('#action').click();await p.waitForTimeout(800);await p.screenshot({path:'.qa/smash-blocks.png',fullPage:true});
 await p.emulateMedia({reducedMotion:'reduce'});await p.locator('[data-scene=glass]').click();for(let i=0;i<3;i++)await p.locator('#action').click();const reduced=await p.locator('#desk').evaluate(c=>c.toDataURL());await p.waitForTimeout(200);assert.equal(await p.locator('#desk').evaluate(c=>c.toDataURL()),reduced);
 await p.locator('#again').click();await p.locator('#action').click();await p.screenshot({path:'.qa/smash-glass.png',fullPage:true});
 const m=await b.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await m.addInitScript(()=>Object.defineProperty(navigator,'vibrate',{value:undefined,configurable:true}));await m.goto(base+'/smash.html');assert.equal(await m.locator('#haptic').isDisabled(),true);await m.locator('[data-scene=bubbles]').click();await m.locator('#desk').scrollIntoViewIfNeeded();const mb=await m.locator('#desk').boundingBox(),cdp=await m.context().newCDPSession(m);const touch=(x,y)=>({x:mb.x+x*mb.width/720,y:mb.y+y*mb.height/460});await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[touch(94,74)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[touch(626,74)]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await m.locator('#desk').getAttribute('data-popped'),'8');assert.equal(await m.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);await m.screenshot({path:'.qa/smash-mobile.png',fullPage:true});assert.deepEqual(errors,[]);
 console.log('PASS: glass cracks/shatter/reset, real audio generation and mute, haptic opt-in, mouse/touch bubble sweeps, keyboard, block drag/release/motion, reduced effects and mobile layout');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1});
